import { PathwayFAQ } from '../components/PathwayFAQ';
import { getPathwayQuestions } from '../data/pathway-faq';
import Link from "next/link";
import { MarketingShell, Section, Intro, CTA, FAQ, Cards, Support } from "../components/Marketing";
import { pageMetadata } from "../lib/seo";

export const metadata=pageMetadata("/per-chi","Corpo Capace: per chi è il percorso","Capisci se un percorso attivo e personalizzato è coerente con le difficoltà e le attività che vuoi recuperare.");
export default function Page(){return <MarketingShell><Intro page="per-chi" label="Per chi è" title="Il punto di partenza è la tua vita." copy="Puoi voler camminare più a lungo, affrontare le scale con più fiducia o riprendere un’attività. Non serve essere sportivi: serve un obiettivo concreto e la disponibilità a lavorarci con continuità."/>
<Section label="Situazioni riconoscibili" title="Quando le attività diventano una rinuncia."><Cards items={[["Riesci a farlo, ma non a lungo","La durata o la frequenza restano inferiori a quelle che vorresti."],["Quando aumenti, ti devi fermare","Una ripartenza è seguita da nuove difficoltà e non sai come regolare il lavoro."],["Non sai se stai facendo bene","Vuoi indicazioni comprensibili e un confronto sulle tue esecuzioni."]]}/><p className="cc-note">Riconoscersi in questi esempi non determina automaticamente l’idoneità al percorso.</p></Section>
<Section dark label="Cosa richiede il percorso" title="La tua partecipazione fa parte del lavoro."><Cards items={[["Esercitarti con continuità","Concordare un impegno compatibile con il tempo e il contesto disponibili."],["Condividere le esecuzioni","Inviare i video richiesti perché il team possa osservare il lavoro."],["Comunicare come rispondi","Segnalare difficoltà, sintomi e recupero per orientare gli adattamenti."]]}/></Section>
<Section label="Appropriatezza" title="Prima di iniziare, capire se è il passo giusto."><div className="cc-split"><div><h3>Quando considerarlo</h3><p>Vuoi recuperare un’attività e cerchi un programma che tenga conto delle tue possibilità, con riscontri e aggiornamenti lungo il percorso.</p></div><div><h3>Quando serve prima una valutazione sanitaria</h3><p>Una condizione acuta, instabile o non chiarita richiede l’inquadramento appropriato.</p></div></div><Link className="cc-link" href="/percorsi">Scopri come si svolge il percorso →</Link></Section><Section label="Approfondisci" title="Capire se è il passo adatto a te."><PathwayFAQ items={getPathwayQuestions(["paura-peggiorare", "diagnosi-referto", "quando-non-scegliere"])}/><Link className="cc-link" href="/domande-frequenti">Tutte le domande sul percorso →</Link></Section><CTA/></MarketingShell>}
