import { articles } from '../data/articles';
import { runningGroups } from '../data/running';
import { topics } from '../data/topics';
import { absolute, editorialPages, INDEXABLE } from './site';
const xml=(s:string)=>s.replace(/[<>&"']/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&apos;'}[c]!));
export function seoResponse(path:string):Response|undefined {
 if(path==='/robots.txt')return new Response(`User-agent: *\n${INDEXABLE?'Allow: /':'Disallow: /'}\nSitemap: ${absolute('/sitemap.xml')}\n`,{headers:{'content-type':'text/plain; charset=utf-8'}});
 if(path==='/sitemap.xml'){const urls=[...['/blog/corsa','/blog/piede-caviglia','/blog/piede-caviglia/tallone-fascia-plantare','/blog/piede-caviglia/tendine-achille','/blog/piede-caviglia/avampiede-metatarsi',...runningGroups.filter(g=>g.active).map(g=>'/blog/corsa/'+g.slug)].map(path=>({url:absolute(path),date:null})),...editorialPages.map(p=>({url:absolute(p.path),date:null})),...topics.map(t=>({url:absolute('/blog/argomenti/'+t.slug),date:null})),...articles.map(a=>({url:absolute('/blog/'+a.slug),date:a.updatedAt??a.publishedAt}))];return new Response('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+urls.map(a=>`<url><loc>${xml(a.url)}</loc>${a.date?`<lastmod>${a.date}</lastmod>`:''}</url>`).join('')+'</urlset>',{headers:{'content-type':'application/xml; charset=utf-8'}});}
 if(path==='/feed.xml')return new Response('<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"><channel><title>Corpo Capace · Dr. Botta</title><link>'+absolute('/blog')+'</link><description>Movimento, carico e ritorno all’attività</description><language>it-it</language>'+articles.map(a=>`<item><title>${xml(a.title)}</title><link>${absolute('/blog/'+a.slug)}</link><guid>${absolute('/blog/'+a.slug)}</guid><description>${xml(a.excerpt)}</description>${a.publishedAt?`<pubDate>${new Date(a.publishedAt+'T12:00:00Z').toUTCString()}</pubDate>`:''}<category>${xml(a.category)}</category></item>`).join('')+'</channel></rss>',{headers:{'content-type':'application/rss+xml; charset=utf-8'}});
}
