import type { Metadata } from 'next';
import type { WithContext, BlogPosting, BreadcrumbList, Organization, Person, WebSite, FAQPage } from 'schema-dts';
import type { Article } from '../data/articles';
import { absolute, INDEXABLE } from './site';
export function pageMetadata(path:string,title:string,description:string,image?:string):Metadata{return {title,description,alternates:{canonical:absolute(path)},robots:{index:INDEXABLE,follow:true},openGraph:{title,description,url:absolute(path),siteName:'Corpo Capace · Dr. Botta',locale:'it_IT',type:'website',...(image?{images:[absolute(image)]}:{})},twitter:{card:image?'summary_large_image':'summary',title,description,...(image?{images:[absolute(image)]}:{})}};}
export function JsonLd({data}:{data:object}){return <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(data).replace(/</g,'\\u003c')}}/>;}
export function Breadcrumbs({items}:{items:{name:string;path:string}[]}){const data:WithContext<BreadcrumbList>={'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:items.map((a,i)=>({'@type':'ListItem',position:i+1,name:a.name,item:absolute(a.path)}))};return <><nav className="breadcrumbs" aria-label="Percorso di navigazione">{items.map((a,i)=><span key={a.path}>{i>0&&<span aria-hidden="true"> / </span>}{i===items.length-1?<span aria-current="page">{a.name}</span>:<a href={a.path}>{a.name}</a>}</span>)}</nav><JsonLd data={data}/></>;}
export function ArticleSchema({article:a}:{article:Article}){const data:WithContext<BlogPosting>={'@context':'https://schema.org','@type':'BlogPosting',headline:a.title,description:a.seoDescription ?? a.description ?? a.excerpt,url:absolute('/blog/'+a.slug),mainEntityOfPage:{'@type':'WebPage','@id':absolute('/blog/'+a.slug)},datePublished:a.publishedAt,...(a.updatedAt?{dateModified:a.updatedAt}:{}),image:absolute(a.image),author:{'@type':'Organization',name:'Team Corpo Capace',url:absolute('/chi-sono')},publisher:{'@type':'Organization',name:'Corpo Capace · Dr. Botta',url:absolute('/')},inLanguage:'it-IT',articleSection:a.category};return <JsonLd data={data}/>;}
export function SiteSchema(){const organization:WithContext<Organization>={'@context':'https://schema.org','@type':'Organization','@id':absolute('/#organization'),name:'Corpo Capace · Dr. Botta',url:absolute('/')};const person:WithContext<Person>={'@context':'https://schema.org','@type':'Person',name:'Simone Botta Lamanna',url:absolute('/chi-sono')};const site:WithContext<WebSite>={'@context':'https://schema.org','@type':'WebSite',name:'Corpo Capace · Dr. Botta',url:absolute('/'),inLanguage:'it-IT'};return <><JsonLd data={organization}/><JsonLd data={person}/><JsonLd data={site}/></>;}

export function ArticleFaqSchema({article}:{article:Article}){const section=article.sections.find(s=>/^(Domande frequenti|FAQ)$/i.test(s.heading));if(!section)return null;const entries=section.paragraphs.flatMap((p,i)=>p.startsWith('### ')&&section.paragraphs[i+1]?[{'@type':'Question' as const,name:p.slice(4),acceptedAnswer:{'@type':'Answer' as const,text:section.paragraphs[i+1].replace(/\*\*/g,'')}}]:[]);if(!entries.length)return null;const data:WithContext<FAQPage>={'@context':'https://schema.org','@type':'FAQPage',mainEntity:entries};return <JsonLd data={data}/>;}
