import Link from "next/link";
import { MarketingShell, Section, Intro, CTA, FAQ, Cards, Support } from "../components/Marketing";
import { pageMetadata } from "../lib/seo";
import { CONSULTATION_URL } from "../lib/site";

export const metadata=pageMetadata("/colloquio","Il primo colloquio con il Team Corpo Capace","Cosa aspettarti dal colloquio sul percorso Corpo Capace, prima di scegliere giorno e orario.");
export default function Page(){return <MarketingShell><Intro page="colloquio" label="Prima di prenotare" title="Un colloquio per capire il percorso." copy="Parlerai con un referente del Team Corpo Capace. L’incontro serve a presentare il funzionamento del percorso, chiarire l’assistenza e orientare i passaggi successivi."/>
<Section label="Cosa aspettarti" title="Arriva con le tue domande."><Cards items={[["La tua esigenza","Racconta quali attività ti limitano e ciò che vorresti recuperare."],["Il funzionamento","Chiarisci come si svolge il programma, come vengono raccolti i riscontri e quale assistenza è prevista."],["Le condizioni","Chiedi durata, impegno, costo e modalità del percorso prima di decidere se aderire."]]}/><div className="cc-panel"><h3>Con chi parlerai</h3><p>Il colloquio è con il team, non con Dr. Botta personalmente.</p></div></Section>
<Section id="calendario" label="Scegli giorno e orario" title="Apri il calendario del team."><p className="cc-lead">Nel calendario controlla i dettagli dell’appuntamento prima di confermare la prenotazione.</p><a className="cc-button" href={CONSULTATION_URL} target="_blank" rel="noopener noreferrer">Scegli un orario nel calendario ↗</a><p className="cc-small">Il calendario si apre in una nuova scheda su Calendly.</p><details className="cc-calendar"><summary>Preferisci visualizzare il calendario qui?</summary><iframe src={CONSULTATION_URL} title="Calendario del Team Corpo Capace" loading="lazy"/><p>Se il calendario incorporato non si carica, <a href={CONSULTATION_URL} target="_blank" rel="noopener noreferrer">aprilo in una nuova scheda</a>.</p></details><p className="cc-note"><Link href="/termini-e-condizioni">Termini e condizioni di servizio</Link> · <a href="https://www.iubenda.com/privacy-policy/48665326" target="_blank" rel="noreferrer">Privacy Policy ↗</a></p></Section></MarketingShell>}
