import { PathwayFAQ } from '../components/PathwayFAQ';
import { getPathwayQuestions } from '../data/pathway-faq';
import Link from "next/link";
import { MarketingShell, Section, Intro, CTA, FAQ, Cards, Support } from "../components/Marketing";
import { pageMetadata } from "../lib/seo";

export const metadata=pageMetadata("/metodo","Come funziona il Metodo Corpo Capace","Valutazione funzionale, esercizio progressivo e monitoraggio: come il team organizza un percorso sulle tue attività.");
export default function Page(){return <MarketingShell><Intro page="metodo" label="Il metodo" title="Capire da dove partire. Sapere come proseguire." copy="Corpo Capace collega il lavoro sugli esercizi alle attività che vuoi recuperare. La tua situazione orienta il punto di partenza; le tue risposte guidano gli adattamenti."/>
<Section label="Il punto di partenza" title="Capace rispetto a ciò che vuoi fare."><div className="cc-split"><p className="cc-lead">Una passeggiata, una rampa di scale e una corsa richiedono capacità diverse. Definiamo prima l’attività che conta per te, poi osserviamo ciò che riesci a sostenere oggi.</p><div className="cc-panel"><h3>Il Gap di Capacità</h3><p>È la distanza tra il tuo punto di partenza e ciò che l’attività richiede. Aiuta a scegliere le priorità e a verificare i progressi.</p></div></div></Section>
<Section dark label="Le capacità su cui lavorare" title="Gli esercizi hanno una direzione."><Cards items={[["Mobilità e controllo","Avere il movimento utile e organizzarlo nel gesto che vuoi recuperare."],["Forza e tolleranza","Sostenere il lavoro, ripeterlo e recuperare in modo compatibile con le tue possibilità."],["Capacità specifica","Trasferire il lavoro alle richieste concrete della passeggiata, delle scale o della tua attività."]]}/></Section>
<Section label="Un ciclo che si adatta" title="Valutare, allenare, osservare, adattare."><Cards items={[["La valutazione orienta","Obiettivo, test funzionali e contesto aiutano a scegliere da dove iniziare."],["L’esercizio produce riscontri","Osserviamo esecuzione, sforzo, sintomi e recupero durante e dopo il lavoro."],["I riscontri guidano le scelte","Il programma può progredire, rimanere stabile o essere modificato: la risposta conta più di una scadenza sul calendario."]]}/><div className="cc-panel"><p className="cc-label">Esempio illustrativo</p><h3>L’esercizio riesce, ma il giorno dopo fai più fatica.</h3><p>Il team considera il lavoro svolto e ciò che riferisci, per valutare se modificare quantità, difficoltà o recupero prima di aumentare la richiesta.</p></div></Section>
<Section label="Il percorso attivo" title="Il lavoro prende forma intorno alle tue attività."><p className="cc-lead">Corpo Capace lavora sulle capacità necessarie alle tue attività. Il programma collega il punto di partenza, il lavoro da svolgere e i riscontri che guidano gli adattamenti.</p><Link className="cc-link" href="/per-chi">Capisci quando considerare il percorso →</Link></Section><Section label="Approfondisci" title="Il ragionamento dietro il programma."><PathwayFAQ items={getPathwayQuestions(["gia-provato", "personalizzazione", "nessun-progresso"])}/><Link className="cc-link" href="/domande-frequenti">Tutte le domande sul percorso →</Link></Section><CTA/></MarketingShell>}
