import Link from "next/link";
import { Header } from "./Header";
import { Footer } from "./Footer";
import type { ReactNode } from "react";
import { PageHero, type InnerPage } from "./PageHero";
import "../inner-pages.css";
export function MarketingShell({children}:{children:ReactNode}){return <div className="cc-inner-site"><Header/><main id="contenuto" className="cc-page cc-inner-page" tabIndex={-1}>{children}</main><Footer/></div>}
export function Section({label,title,children,dark=false,id}:{label:string;title:string;children:ReactNode;dark?:boolean;id?:string}){return <section id={id} className={`cc-section${dark?" cc-dark":""}`}><div className="cc-wrap"><div className="cc-section-heading"><p className="cc-label">{label}</p><h2>{title}</h2></div>{children}</div></section>}
export function Intro({page,label,title,copy,children}:{page:InnerPage;label:string;title:string;copy:string;children?:ReactNode}){return <><PageHero page={page}/><section className="cc-inner-intro"><div className="cc-wrap"><div className="cc-intro-grid"><div><p className="cc-label">{label}</p><h2>{title}</h2></div><p className="cc-lead">{copy}</p></div>{children&&<div className="cc-intro-tools">{children}</div>}</div></section></>}
export function CTA({title="Capisci se Corpo Capace fa al caso tuo."}:{title?:string}){return <section className="cc-section cc-dark cc-cta"><div className="cc-wrap cc-split"><div><p className="cc-label">Il primo colloquio</p><h2>{title}</h2><p>Confrontati con un referente del Team Corpo Capace sul funzionamento del percorso, sull’assistenza e sui passaggi per iniziare.</p></div><div><Link className="cc-button cc-button-light" href="/colloquio">Il colloquio con il team <span aria-hidden="true">→</span></Link><Link className="cc-link" href="/domande-frequenti">Hai ancora dubbi? Leggi le risposte</Link></div></div></section>}
export function FAQ({items}:{items:[string,string][]}){return <div className="cc-faq">{items.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div>}
export function Cards({items}:{items:[string,string][]}){return <div className="cc-cards">{items.map(([title,copy],i)=><article key={title}><span className="cc-number">{String(i+1).padStart(2,'0')}</span><h3>{title}</h3><p>{copy}</p></article>)}</div>}
export function Support(){return <Section id="chi-ti-segue" label="Chi ti accompagna" title="Un riferimento durante il percorso. Un metodo che guida il lavoro."><p className="cc-lead">Il Team Corpo Capace applica il metodo alla tua situazione: costruisce il programma, raccoglie i tuoi riscontri e adatta il lavoro.</p><Cards items={[["Indicazioni comprensibili","Video dimostrativi e istruzioni ti aiutano a capire gli esercizi e il lavoro da svolgere."],["Confronto sulle esecuzioni","Invii i tuoi video e segnali le difficoltà. Il team osserva l’esecuzione e fornisce indicazioni sul programma."],["Adattamenti nel tempo","Esecuzione, sintomi, sforzo e recupero orientano gli aggiornamenti. Modalità e frequenza dell’assistenza vengono definite nel percorso concordato."]]}/><Link className="cc-link" href="/team">Conosci il ruolo del team →</Link></Section>}
