import Link from "next/link";
import { MarketingShell, Section, Intro, CTA, FAQ, Cards, Support } from "../components/Marketing";
import { pageMetadata } from "../lib/seo";
import { ResponsiveImage } from "../components/ResponsiveImage";

export const metadata=pageMetadata("/chi-sono","L’origine di Corpo Capace | Simone Botta Lamanna","Il ruolo di Simone Botta Lamanna come ideatore del Metodo Corpo Capace e la sua applicazione da parte del team.");
export default function Page(){return <MarketingShell><Intro page="chi-sono" label="L’origine del metodo" title="Dall’idea di Dr. Botta al percorso Corpo Capace." copy="Un metodo costruito attorno a una domanda: quali capacità servono alla persona per tornare alle attività che contano per lei?"/>
<Section label="L’ideatore" title="Simone Botta Lamanna"><div className="cc-founder"><ResponsiveImage src="/images/dr-botta-giacca-blu.webp" width="1125" height="1687" sizes="(max-width:700px) 160px,220px" loading="eager" fetchPriority="high" alt="Simone Botta Lamanna, ideatore del Metodo Corpo Capace"/><div><p>Simone Botta Lamanna ha ideato Corpo Capace per collegare il lavoro sulle capacità fisiche alle attività che la persona desidera recuperare.</p><p>Camminare più a lungo, affrontare le scale, tornare ad allenarsi: l’obiettivo orienta valutazione, esercizi e progressione.</p><a className="cc-link" href="https://www.linkedin.com/in/bottalamanna/" target="_blank" rel="noreferrer">Profilo professionale su LinkedIn ↗</a></div></div></Section>
<Section dark label="Dal fondatore al metodo" title="Un riferimento comune per il lavoro del team."><p className="cc-lead">Corpo Capace dà struttura al percorso attraverso valutazione funzionale, esercizio progressivo e monitoraggio. Il team applica questi criteri alla situazione individuale.</p><p>Il ruolo di Simone Botta Lamanna è quello di ideatore. Il percorso operativo e il colloquio presentati nel sito sono affidati al Team Corpo Capace.</p><Link className="cc-link" href="/team">Chi segue il percorso →</Link></Section>
<Section label="La redazione" title="Capire le scelte, oltre agli esercizi."><p>Gli approfondimenti del blog sono pubblicati dalla redazione del Team Corpo Capace. Le fonti sono riportate negli articoli; una revisione clinica viene indicata solo quando documentata.</p><Link className="cc-link" href="/blog">Leggi gli approfondimenti →</Link></Section><CTA/></MarketingShell>}
