import Link from 'next/link';
import { MarketingShell, Section, Intro, CTA } from '../components/Marketing';
import { pageMetadata } from '../lib/seo';
import { CareersForm } from '../components/CareersForm';
import './team.css';

export const metadata=pageMetadata('/team','Il Team Corpo Capace | Persone, competenze e metodo','Un lavoro di squadra tra valutazione, programmazione dell’esercizio, coaching e organizzazione rende possibile ogni percorso Corpo Capace.');

export default function Page(){return <MarketingShell>
<Intro page="team" label="Il Team Corpo Capace" title="Dietro ogni percorso c’è il lavoro di più persone." copy="Corpo Capace nasce dal metodo sviluppato da Simone Botta Lamanna e prende forma grazie a un team con competenze complementari. Valutazione, programmazione, coaching e organizzazione lavorano insieme perché il percorso possa essere seguito, discusso e aggiornato nel tempo."/>
<Section label="Come lavoriamo" title="Una persona di riferimento. Una squadra alle spalle."><div className="team-lead"><p>Durante il percorso hai un riferimento a cui inviare video, difficoltà e aggiornamenti. Dietro quel confronto ci sono criteri condivisi, supervisione del lavoro e persone che si occupano delle diverse fasi: dall’ingresso nel percorso alla revisione del programma.</p><p>Il risultato non dipende da un esercizio isolato o dalla presenza continua del fondatore. Dipende dalle decisioni prese lungo il percorso e dalla possibilità di correggere la direzione quando ciò che fai nella vita quotidiana cambia.</p></div><div className="team-workflow" aria-label="Le quattro aree del lavoro di squadra"><article><span>01</span><h3>Ascolto e valutazione</h3><p>Raccogliamo la storia, i video e le attività che vuoi tornare a fare. I test funzionali aiutano a scegliere da dove iniziare.</p></article><article><span>02</span><h3>Programmazione</h3><p>Il lavoro viene tradotto in esercizi, indicazioni pratiche e una progressione adatta al punto di partenza.</p></article><article><span>03</span><h3>Coaching e confronto</h3><p>Il coach osserva le esecuzioni, raccoglie i tuoi riscontri e ti aiuta a capire cosa modificare nella pratica.</p></article><article><span>04</span><h3>Coordinamento e revisione</h3><p>Il team mantiene ordinati passaggi e comunicazioni. Il confronto interno supporta le scelte quando il caso richiede un’ulteriore revisione.</p></article></div></Section>
<Section dark label="Competenze complementari" title="Il metodo tiene insieme i pezzi."><div className="team-dark-grid"><p>La lettura del movimento e dei sintomi, la costruzione dell’allenamento, il feedback sulle esecuzioni e il supporto organizzativo rispondono a bisogni diversi. Servono tutti perché una persona possa applicare il programma nella propria settimana.</p><p>Simone Botta Lamanna ha sviluppato il Metodo Corpo Capace. Il team lo applica, si confronta sui riscontri e segue l’operatività dei percorsi. <Link href="/chi-sono">Scopri l’origine del metodo</Link>.</p></div></Section>
<Section label="Nel tuo percorso" title="Sai con chi parlare e cosa succede dopo."><div className="team-assurance"><p>All’inizio vengono chiariti il tuo riferimento, le modalità di invio dei video e i momenti di confronto previsti. Durante il lavoro segnali come rispondi agli esercizi e che cosa riesci a fare fuori dall’allenamento. Queste informazioni guidano gli aggiornamenti del programma.</p><Link className="cc-link" href="/percorsi">Guarda come funziona il percorso →</Link></div></Section>
<Section id="lavora-con-noi" label="Lavora con noi" title="Porta le tue competenze in Corpo Capace."><div className="team-careers"><div><p>Ci interessano professionisti che sappiano osservare il movimento, programmare esercizio e lavorare in squadra, ma anche persone capaci di rendere chiari e affidabili il supporto e l’organizzazione del percorso.</p><p>Se condividi un approccio attivo e sai trasformare una valutazione in indicazioni comprensibili, raccontaci il tuo lavoro. Valutiamo candidature spontanee in base alle esigenze del team.</p></div><div className="team-careers-action"><h3>Presentati al team</h3><p>Scegli il ruolo, raccontaci la tua esperienza e allega il CV quando si apre il messaggio.</p><CareersForm/></div></div></Section>
<CTA title="Conosci le persone e il metodo dietro al tuo percorso."/>
</MarketingShell>}
