import Link from "next/link";
import { MarketingShell, Section, Intro, CTA, FAQ, Cards, Support } from "../components/Marketing";
import { pageMetadata } from "../lib/seo";
const stories = [
  { name: "Vincenzo", date: "19 agosto 2026", title: "Ha ritrovato fiducia nella corsa", tag: "CORSA · ANCA", copy: "Dopo una maratona conviveva con dolore all’anca, all’inguine e alla zona lombare. Un percorso strutturato, con esercizi e feedback continui, gli ha permesso di gestire le ricadute e tornare a correre con maggiore fiducia nel proprio corpo." },
  { name: "Alessandra", date: "21 maggio 2026", title: "È tornata a camminare", tag: "CAMMINO · PIEDE", copy: "Dopo oltre un anno di fascite plantare e diversi tentativi senza il risultato sperato, ha trovato un percorso progressivo e una guida costante. Il traguardo più concreto: tornare a camminare senza il limite che condizionava le sue giornate." },
  { name: "Alessandro", date: "5 maggio 2026", title: "Di nuovo ai suoi livelli", tag: "SPORT · PERFORMANCE", copy: "Atleta professionista, era limitato da problemi a spalla, ginocchio e anca. Dopo mesi di lavoro metodico ha recuperato stabilità, equilibrio e mobilità, tornando progressivamente ai livelli precedenti." },
];

const reviews = [
  { name: "Simona", date: "5 agosto 2026", title: "Mai seguita più di così", copy: "Un programma costruito sui suoi bisogni e sul tempo disponibile, con feedback continui e una relazione capace di farla sentire compresa." },
  { name: "M.M.", date: "10 luglio 2026", title: "Di nuovo alla sua attività", copy: "Un programma mirato e professionisti presenti l’hanno aiutato a gestire un problema che durava da anni e a riprendere l’attività." },
  { name: "Michele", date: "29 giugno 2026", title: "Dallo scetticismo alla corsa", copy: "Era dubbioso sul percorso a distanza. La continuità del supporto e i risultati ottenuti gli hanno permesso di tornare a correre." },
  { name: "Dania", date: "19 giugno 2026", title: "Tornare a correre", copy: "Descrive un team preparato e disponibile e un percorso che le ha consentito di riprendere la corsa senza i dolori che la fermavano." },
  { name: "Pierdaniel", date: "24 maggio 2026", title: "Seguito passo dopo passo", copy: "Video chiari, confronti regolari e presenza costante hanno reso il percorso comprensibile, concreto e facile da seguire." },
  { name: "Andrea", date: "28 aprile 2026", title: "Il valore dei feedback", copy: "Alla prima esperienza a distanza, ha visto miglioramenti in poche settimane grazie ai controlli e agli adattamenti del programma." },
  { name: "Claudia", date: "24 aprile 2026", title: "Più autonomia ogni giorno", copy: "Un problema all’anca limitava anche gesti semplici. Un programma adattato a lei ha migliorato concretamente la qualità della vita quotidiana." },
];

export const metadata=pageMetadata('/testimonianze','Esperienze con Corpo Capace | Recensioni','Esperienze di attività recuperate e supporto ricevuto. Sintesi e collegamento alle recensioni originali su Trustpilot.');
export default function Page(){const ordered=[stories[1],...reviews.filter(r=>r.name==='Claudia'||r.name==='Simona'),stories[0],stories[2],...reviews.filter(r=>r.name!=='Claudia'&&r.name!=='Simona')];return <MarketingShell><Intro page="testimonianze" label="Le esperienze" title="Attività recuperate. Supporto vissuto." copy="Esperienze personali di chi ha seguito un percorso. Le sintesi rimandano alle recensioni pubblicate su Trustpilot."/><Section label="Voci dal percorso" title="Obiettivi diversi, esperienze personali."><div className="cc-stories">{ordered.map(r=><article key={r.name}><h3>{r.title}</h3><p>{r.copy}</p><small>{r.name} · {r.date}</small></article>)}</div><p className="cc-note">Sintesi delle recensioni pubblicate su Trustpilot. Consulta i testi integrali per conoscere il contesto di ogni esperienza.</p></Section><Section label="La fonte" title="Leggi le recensioni complete."><p>Le recensioni integrali, con date e profili degli autori, sono disponibili sul profilo Trustpilot di Dr. Botta. Puoi consultarle prima di scegliere.</p><a className="cc-button" href="https://it.trustpilot.com/review/drbotta.com" target="_blank" rel="noopener noreferrer">Apri le recensioni su Trustpilot ↗</a></Section><CTA/></MarketingShell>}
