import Link from 'next/link';
import {MarketingShell,Intro,Section,CTA} from '../components/Marketing';
import {PathwayFAQ} from '../components/PathwayFAQ';
import {faqGroups,pathwayQuestions} from '../data/pathway-faq';
import {pageMetadata,JsonLd} from '../lib/seo';
import {absolute} from '../lib/site';
export const metadata=pageMetadata('/domande-frequenti','Corpo Capace: domande su metodo, team e percorso online','Risposte approfondite su Corpo Capace: chi ti segue, come funziona online, paura degli esercizi, impegno, risultati e condizioni prima del colloquio.');
export default function Page(){return <MarketingShell><Intro page="domande-frequenti" label="La guida prima di scegliere" title="Capire il percorso, prima di decidere." copy="Se hai già provato altre strade, è normale voler capire meglio prima di affidarti a un nuovo percorso. Qui trovi risposte su metodo, assistenza e impegno, anche quando la risposta aiuta a capire che serve un altro primo passo."><nav aria-label="Argomenti delle domande frequenti" className="cc-faq-index">{faqGroups.map(group=><a key={group.id} href={'#'+group.id}>{group.title}</a>)}</nav></Intro>
<Section label="Corpo Capace, in breve" title="Un metodo, un team, la tua partecipazione."><p className="cc-lead">Corpo Capace è il metodo di esercizio personalizzato ideato da Simone Botta Lamanna. Il team segue il percorso operativo: programma, riscontri sulle esecuzioni e adattamenti. Il lavoro parte dalle attività che vuoi recuperare e dalle possibilità attuali, anche a casa o in palestra.</p><p>Il primo colloquio riguarda il percorso e avviene con il team. <Link href="/team">Scopri chi fa cosa</Link>.</p></Section>
{faqGroups.map(group=><Section key={group.id} id={group.id} label="Le tue domande" title={group.title}><p className="cc-lead">{group.intro}</p><PathwayFAQ expanded items={pathwayQuestions.filter(q=>q.group===group.id)}/></Section>)}
<Section dark label="Prima del colloquio" title="Tre cose da mettere a fuoco."><ol className="cc-readiness"><li><strong>Il tuo obiettivo.</strong> Quale attività vorresti recuperare e cosa ti limita oggi?</li><li><strong>La partecipazione possibile.</strong> Hai modo di esercitarti e condividere i video richiesti?</li><li><strong>Il supporto che cerchi.</strong> Vuoi un percorso con il team, oppure stai cercando una visita o un appuntamento con il fondatore?</li></ol><p>Queste domande aiutano a orientarti: non sono un test clinico e non stabiliscono l’idoneità al percorso.</p></Section><CTA/>
<JsonLd data={{'@context':'https://schema.org','@type':'WebPage','@id':absolute('/domande-frequenti#webpage'),url:absolute('/domande-frequenti'),name:'Domande frequenti sul percorso Corpo Capace',inLanguage:'it-IT',about:{'@id':absolute('/#organization')},isPartOf:{'@id':absolute('/#website')}}}/>
</MarketingShell>}
