import Link from 'next/link';
import {Header} from './components/Header';
import {Footer} from './components/Footer';
import {HomeHero} from './components/HomeHero';
import {ResponsiveImage} from './components/ResponsiveImage';
import {PathwayFAQ} from './components/PathwayFAQ';
import {getPathwayQuestions} from './data/pathway-faq';
import {pageMetadata} from './lib/seo';
import {articles} from './data/articles';
import './home-atlante.css';
export const metadata=pageMetadata('/','Corpo Capace | Percorsi online per tornare a muoverti','Percorsi online di esercizio personalizzato per chi convive con dolore a schiena, anca, ginocchio o piede. Scopri il metodo e il Team Corpo Capace.');
const steps=[
 ['Parliamone insieme','Racconta al team cosa ti limita e cosa vuoi tornare a fare. Chiarisci come funziona il percorso.'],
 ['Partiamo da te','Condividi la tua storia e i video richiesti: servono a capire come ti muovi e da dove iniziare.'],
 ['Inizia il tuo programma','Ricevi gli esercizi, i video dimostrativi e le indicazioni per allenarti a casa o in palestra.'],
 ['Andiamo avanti insieme','Invia le esecuzioni e racconta come va. Il team ti dà indicazioni e aggiorna il programma.'],
];
export default function Home(){return <div className="cc-home-site"><Header home/><main id="contenuto" className="cc-page cc-home" tabIndex={-1}>
<HomeHero/>
<div className="cc-home-strip"><span>Esercizi su misura</span><span>Correzioni dei tuoi video</span><span>Un team che ti segue</span></div>
<section id="chi-siamo" className="cc-home-section"><div className="cc-home-container"><div className="cc-home-heading"><p className="cc-home-kicker">Chi siamo</p><h2>Siamo Corpo Capace.<br/>Ti aiutiamo a riprendere<br/><em>le attività che ami.</em></h2></div>
<div className="cc-home-about"><figure><ResponsiveImage src="/images/ginocchio-step.webp" alt="Una donna si esercita su un rialzo a casa" sizes="(max-width: 760px) 94vw, 45vw" loading="lazy"/><figcaption>Il lavoro negli esercizi. Il valore nella tua giornata.</figcaption></figure><div><p className="cc-home-intro">Un percorso online per chi vuole tornare a camminare, fare le scale, allenarsi o praticare sport quando il dolore rende tutto più difficile.</p><p>Il <strong>Metodo Corpo Capace</strong> parte da ciò che oggi riesci a fare. Il team costruisce il programma, osserva i tuoi video e ti aiuta a svolgere gli esercizi nel modo previsto.</p><p>Le tue risposte guidano il lavoro: cosa diventa più semplice, dove incontri difficoltà e come ti senti dopo. Da qui decidiamo insieme i passi successivi.</p><Link className="cc-home-button cc-home-button-green" href="/metodo">Conosci il metodo <span aria-hidden="true">↗</span></Link></div></div>
</div></section>
<section className="cc-home-section cc-home-navy" id="chi-ti-segue"><div className="cc-home-container"><div className="cc-home-heading cc-home-centered"><p className="cc-home-kicker">Come ti seguiamo</p><h2>Un programma per te.<br/><em>Qualcuno con cui confrontarti.</em></h2><p>Dal primo esercizio agli aggiornamenti, sai che cosa fare e a chi rivolgerti.</p></div><div className="cc-home-services">
<article><span className="cc-home-number">01</span><h3>Esercizi su misura</h3><p>Il lavoro tiene conto delle attività che vuoi recuperare, del tempo e dell’attrezzatura che hai.</p></article>
<article><span className="cc-home-number">02</span><h3>Indicazioni sui tuoi video</h3><p>Invii le esecuzioni. Il team le osserva e ti spiega cosa mantenere e cosa correggere.</p></article>
<article><span className="cc-home-number">03</span><h3>Un percorso che si aggiorna</h3><p>Racconti come va negli esercizi e nella tua giornata. Il programma cambia seguendo i tuoi riscontri.</p></article>
<div className="cc-home-service-cta"><h3>Vuoi capire come funziona nella pratica?</h3><p>Scopri i passaggi e il ruolo del team.</p><Link href="/percorsi" className="cc-home-button cc-home-button-green">Il percorso <span aria-hidden="true">↗</span></Link></div>
</div></div></section>
<section className="cc-home-section"><div className="cc-home-container"><div className="cc-home-heading cc-home-centered"><p className="cc-home-kicker">Da dove vuoi ripartire?</p><h2>Le cose che ti mancano.<br/><em>Gli obiettivi su cui lavorare.</em></h2></div><div className="cc-home-goals">
<article><ResponsiveImage src="/images/corsa-ricreativa-articolazioni.webp" alt="Due adulti si muovono insieme su un sentiero nel parco" sizes="(max-width: 760px) 94vw, 31vw" loading="lazy"/><div><h3>Uscire e muoverti di più</h3><p>Una passeggiata, una gita, tempo all’aperto. Ripartire dalle attività che rendono più tua la giornata.</p></div></article>
<article><ResponsiveImage src="/images/ginocchio-step.webp" alt="Esercizio su un rialzo, con appoggio al corrimano" sizes="(max-width: 760px) 94vw, 31vw" loading="lazy"/><div><h3>Ritrovare autonomia</h3><p>Fare le scale, alzarti, sbrigare le commissioni. Lavorare sui gesti che oggi ti mettono in difficoltà.</p></div></article>
<article><ResponsiveImage src="/images/equilibrio-monopodalico.webp" alt="Un uomo si allena in equilibrio su una gamba" sizes="(max-width: 760px) 94vw, 31vw" loading="lazy"/><div><h3>Riprendere ad allenarti</h3><p>La palestra, la corsa o il tuo sport. Costruire il ritorno all’attività un passo alla volta.</p></div></article>
</div><div className="cc-home-centered"><Link className="cc-home-text-link" href="/per-chi">Scopri a chi si rivolge Corpo Capace →</Link></div></div></section>
<section className="cc-home-section cc-home-ice"><div className="cc-home-container"><div className="cc-home-heading cc-home-centered"><p className="cc-home-kicker">Come iniziare</p><h2>Il primo passo è <em>parlarne.</em></h2><p>Ti accompagniamo dal primo confronto al lavoro nella tua settimana.</p></div><ol className="cc-home-steps">{steps.map(([title,copy],i)=><li key={title}><span aria-hidden="true">0{i+1}</span><h3>{title}</h3><p>{copy}</p></li>)}</ol><div className="cc-home-centered"><Link href="/colloquio" className="cc-home-button cc-home-button-green">Prenota la tua consulenza <span aria-hidden="true">↗</span></Link></div></div></section>
<section className="cc-home-section"><div className="cc-home-container"><div className="cc-home-heading cc-home-centered"><p className="cc-home-kicker">Le esperienze di chi ci ha scelto</p><h2>Il cambiamento si racconta<br/><em>con le cose che torni a fare.</em></h2></div><div className="cc-home-reviews">
<article><p className="cc-home-review-topic">Tornare a camminare</p><h3>Alessandra</h3><p>Dopo oltre un anno di fascite plantare, racconta di essere tornata a camminare senza il limite che condizionava le sue giornate.</p><small>21 maggio 2026 · Sintesi da Trustpilot</small></article>
<article><p className="cc-home-review-topic">Sentirsi seguiti</p><h3>Simona</h3><p>Descrive un programma costruito sui suoi bisogni e sul tempo disponibile, con feedback e una guida presente.</p><small>5 agosto 2026 · Sintesi da Trustpilot</small></article>
<article><p className="cc-home-review-topic">Più autonomia ogni giorno</p><h3>Claudia</h3><p>Un problema all’anca limitava anche gesti semplici. Racconta come un programma adattato a lei abbia migliorato la sua vita quotidiana.</p><small>24 aprile 2026 · Sintesi da Trustpilot</small></article>
</div><div className="cc-home-review-links"><Link className="cc-home-text-link" href="/testimonianze">Leggi le esperienze →</Link><a className="cc-home-text-link" href="https://it.trustpilot.com/review/drbotta.com" target="_blank" rel="noopener noreferrer">Consulta le recensioni su Trustpilot ↗</a></div></div></section>
<section className="cc-home-section cc-home-founder"><div className="cc-home-container cc-home-founder-grid"><ResponsiveImage src="/images/dr-botta-giacca-blu.webp" alt="Simone Botta Lamanna, ideatore del Metodo Corpo Capace" sizes="(max-width: 760px) 150px, 250px" loading="lazy"/><div><p className="cc-home-kicker">L’origine del metodo</p><h2>Ideato da Dr. Botta.<br/><em>Seguito dal team.</em></h2><p>Simone Botta Lamanna ha sviluppato Corpo Capace per collegare il lavoro negli esercizi alle attività che la persona vuole recuperare.</p><p>Il Team Corpo Capace segue il tuo percorso: costruisce il programma, raccoglie i tuoi video e ti accompagna negli aggiornamenti.</p><div className="cc-home-inline-links"><Link className="cc-home-text-link" href="/team">Conosci il ruolo del team →</Link><Link className="cc-home-text-link" href="/chi-sono">Conosci Dr. Botta →</Link></div></div></div></section>
<section className="cc-home-section"><div className="cc-home-container cc-home-faq-layout"><div><p className="cc-home-kicker">Prima di scegliere</p><h2>Le tue domande.<br/><em>Risposte concrete.</em></h2><Link className="cc-home-text-link" href="/domande-frequenti">Tutte le domande frequenti →</Link></div><PathwayFAQ items={getPathwayQuestions(['eta-e-allenamento','perche-team','online','tempo'])}/></div></section>
<section className="cc-home-final"><ResponsiveImage src="/images/corsa-ricreativa-articolazioni.webp" alt="" sizes="100vw" loading="lazy"/><div className="cc-home-final-shade"/><div className="cc-home-container"><p className="cc-home-kicker">Inizia da ciò che conta per te</p><h2>Che cosa vuoi<br/><em>tornare a fare?</em></h2><p>Raccontalo al Team Corpo Capace. Nel primo colloquio puoi conoscere il percorso, chiarire i tuoi dubbi e capire come iniziare.</p><Link className="cc-home-button" href="/colloquio">Prenota la tua consulenza <span aria-hidden="true">↗</span></Link></div></section>
<section className="cc-home-section cc-home-reading"><div className="cc-home-container"><div className="cc-home-heading"><p className="cc-home-kicker">Per approfondire</p><h2>Capire meglio il tuo movimento.</h2><p>Esplora gli articoli e le risorse di Corpo Capace.</p></div><div className="cc-home-articles">{articles.slice(0,3).map(article=><Link href={`/blog/${article.slug}`} key={article.slug}><span>{article.category}</span><h3>{article.title}</h3><strong>Leggi l’articolo →</strong></Link>)}</div><div className="cc-home-inline-links"><Link className="cc-home-text-link" href="/blog">Tutti gli articoli →</Link><Link className="cc-home-text-link" href="/guide">Guide e strumenti →</Link></div></div></section>
</main><Footer/></div>}
