import Link from 'next/link';
import {Header} from './components/Header';
import {Footer} from './components/Footer';
import {HomeHero} from './components/HomeHero';
import {ResponsiveImage} from './components/ResponsiveImage';
import {PathwayFAQ} from './components/PathwayFAQ';
import {getPathwayQuestions} from './data/pathway-faq';
import {pageMetadata} from './lib/seo';
import './home-atlante.css';

export const metadata=pageMetadata('/','Corpo Capace | Torna alle attività che contano per te','Percorsi online di esercizio personalizzato per recuperare abilità e tolleranza al carico. Scopri il Metodo Corpo Capace, Dr. Botta e i professionisti che seguono il percorso.');
const steps=[
 ['Il tuo obiettivo','Definiamo l’attività che vuoi recuperare e le richieste da preparare.'],
 ['Il punto di partenza','Storia, attività attuali e video aiutano il professionista a osservare come ti muovi e cosa riesci a sostenere.'],
 ['Il programma','Ricevi esercizi, video dimostrativi e indicazioni: il lavoro tiene conto delle tue possibilità, del tempo e dell’attrezzatura.'],
 ['I tuoi riscontri','Invii le esecuzioni e racconti sintomi, difficoltà, sforzo e recupero, anche nella vita quotidiana.'],
 ['Gli adattamenti','Il professionista rilegge la risposta e decide se aumentare la richiesta, mantenerla o modificare il lavoro.'],
];
const reading=[
 {href:'/metodo',label:'Comprendere',title:'Che cosa significa un Corpo Capace?',copy:'Obiettivi, capacità e progressione: il ragionamento che guida gli esercizi.',action:'Esplora il metodo'},
 {href:'/domande-frequenti',label:'Chiarire',title:'Come funziona il percorso per me?',copy:'Assistenza online, personalizzazione, impegno e ruolo dei professionisti.',action:'Leggi le risposte'},
 {href:'/blog',label:'Approfondire',title:'Dolore, movimento e ritorno all’attività.',copy:'Scegli l’argomento che ti riguarda e approfondisci le domande sul movimento.',action:'Esplora la biblioteca'},
];

export default function Home(){return <div className="cc-home-site"><Header home/><main id="contenuto" className="cc-page cc-home" tabIndex={-1}>
<HomeHero/>
<div className="cc-home-strip"><span>Esercizio personalizzato</span><span>Feedback sulle esecuzioni</span><span>Professionisti che ti seguono</span></div>

<section id="chi-siamo" className="cc-home-section"><div className="cc-home-container"><div className="cc-home-heading cc-home-centered"><p className="cc-home-kicker">Quando il dolore restringe le tue scelte</p><h2>Le attività che ti mancano.<br/><em>Il punto da cui ripartire.</em></h2><p>Magari hai già provato trattamenti o esercizi. Adesso vuoi capire come tornare a fare ciò che continua a metterti in difficoltà.</p></div><div className="cc-home-goals">
<article><ResponsiveImage src="/images/corsa-ricreativa-articolazioni.webp" alt="Due adulti camminano su un sentiero nel parco" sizes="(max-width: 760px) 94vw, 31vw" loading="lazy"/><div><h3>Accorci le passeggiate.</h3><p>Scegli il tragitto pensando alle pause, alle panchine o a quanto sarà faticoso il ritorno. Vorresti poter uscire con più libertà.</p></div></article>
<article><ResponsiveImage src="/images/ginocchio-step.webp" alt="Una donna si esercita su un rialzo con un appoggio" sizes="(max-width: 760px) 94vw, 31vw" loading="lazy"/><div><h3>Eviti alcuni gesti quotidiani.</h3><p>Scale, alzarti da terra, commissioni. Attività che prima erano abituali ora richiedono attenzione o l’aiuto di qualcuno.</p></div></article>
<article><ResponsiveImage src="/images/equilibrio-monopodalico.webp" alt="Un uomo esegue un esercizio in appoggio su una gamba" sizes="(max-width: 760px) 94vw, 31vw" loading="lazy"/><div><h3>Riparti, poi ti fermi di nuovo.</h3><p>Provi a tornare in palestra o a correre, ma quando aumenti il lavoro incontri difficoltà. Ti manca una direzione per proseguire.</p></div></article>
</div><div className="cc-home-centered"><Link className="cc-home-text-link" href="/per-chi">Scopri quando considerare il percorso</Link></div></div></section>

<section className="cc-home-section cc-home-ice"><div className="cc-home-container"><div className="cc-home-heading"><p className="cc-home-kicker">Che cosa significa Corpo Capace</p><h2>Come ti senti.<br/><em>Che cosa riesci a fare.</em></h2></div><div className="cc-home-about"><figure><ResponsiveImage src="/images/ginocchio-step.webp" alt="Esercizio su un rialzo per lavorare sulle richieste del movimento" sizes="(max-width: 760px) 94vw, 45vw" loading="lazy"/><figcaption>Il riferimento è l’attività che vuoi recuperare.</figcaption></figure><div><p className="cc-home-intro">Il dolore conta. Per costruire il percorso osserviamo anche quanto movimento riesci a sostenere oggi e che cosa vorresti tornare a fare.</p><p>Puoi sentirti meglio e restare incerto sulle scale o lontano dalla corsa. Il lavoro collega i tuoi riscontri alle capacità richieste da quelle attività.</p><p>Corpo Capace parte da questa distanza: <strong>tra ciò che riesci a fare oggi e ciò che il tuo obiettivo richiede.</strong> Da qui scegliamo le priorità, la quantità di lavoro e i passi successivi.</p><Link className="cc-home-button cc-home-button-green" href="/metodo">Comprendi il Metodo Corpo Capace</Link></div></div></div></section>

<section className="cc-home-section cc-home-navy" id="come-lavoriamo"><div className="cc-home-container"><div className="cc-home-heading cc-home-centered"><p className="cc-home-kicker">Il metodo nella pratica</p><h2>Ogni scelta ha una direzione.<br/><em>I tuoi riscontri guidano il lavoro.</em></h2><p>Un percorso online che collega valutazione funzionale, esercizio e confronto con il professionista.</p></div><ol className="cc-home-method-steps">{steps.map(([title,copy],i)=><li key={title}><span className="cc-home-number" aria-hidden="true">0{i+1}</span><h3>{title}</h3><p>{copy}</p></li>)}</ol><aside className="cc-home-example" aria-labelledby="home-example-title"><p className="cc-home-kicker">Esempio illustrativo</p><h3 id="home-example-title">Completi il lavoro, ma il giorno dopo le scale diventano più faticose.</h3><p>Il team considera esercizi, attività della giornata e recupero. Può rivedere la dose o la distribuzione del lavoro prima di aumentare la richiesta. Il programma viene adattato alla risposta osservata.</p></aside><div className="cc-home-centered"><Link href="/percorsi" className="cc-home-button">Scopri come si svolge il percorso</Link></div></div></section>

<section className="cc-home-section"><div className="cc-home-container"><div className="cc-home-heading cc-home-centered"><p className="cc-home-kicker">Le esperienze</p><h2>Attività recuperate.<br/><em>Supporto raccontato da chi lo ha vissuto.</em></h2><p>Esperienze personali, sintetizzate dalle recensioni pubblicate su Trustpilot.</p></div><div className="cc-home-reviews">
<article><p className="cc-home-review-topic">Tornare a camminare</p><h3>Alessandra</h3><p>Dopo oltre un anno di fascite plantare, racconta di essere tornata a camminare senza il limite che condizionava le sue giornate.</p><small>21 maggio 2026 · Sintesi da Trustpilot</small></article>
<article><p className="cc-home-review-topic">Un programma applicabile</p><h3>Simona</h3><p>Descrive un programma costruito sui suoi bisogni e sul tempo disponibile, con feedback e una guida presente.</p><small>5 agosto 2026 · Sintesi da Trustpilot</small></article>
<article><p className="cc-home-review-topic">Più autonomia quotidiana</p><h3>Claudia</h3><p>Un problema all’anca limitava anche gesti semplici. Racconta come un programma adattato a lei abbia migliorato la sua vita quotidiana.</p><small>24 aprile 2026 · Sintesi da Trustpilot</small></article>
</div><div className="cc-home-review-links"><Link className="cc-home-text-link" href="/testimonianze">Leggi le esperienze</Link><a className="cc-home-text-link" href="https://it.trustpilot.com/review/drbotta.com" target="_blank" rel="noopener noreferrer">Consulta le recensioni originali su Trustpilot</a></div></div></section>

<section className="cc-home-section cc-home-founder" id="chi-ti-segue"><div className="cc-home-container cc-home-founder-grid"><ResponsiveImage src="/images/dr-botta-giacca-blu.webp" alt="Simone Botta Lamanna, fondatore di Corpo Capace" sizes="(max-width: 760px) 150px, 250px" loading="lazy"/><div><p className="cc-home-kicker">Le persone dietro al percorso</p><h2>Ideato da Dr. Botta.<br/><em>Seguito dal team.</em></h2><p>Simone Botta Lamanna sviluppa il Metodo Corpo Capace e ne segue la direzione scientifica. La sua esperienza professionale e personale ha orientato il progetto verso il recupero delle abilità nelle persone con dolore persistente.</p><p>I percorsi sono seguiti da <strong>chinesiologi o fisioterapisti del team</strong>. Raccolgono le informazioni, costruiscono il programma, osservano le esecuzioni e guidano gli aggiornamenti. Collaboriamo con medici quando il lavoro richiede il loro contributo.</p><div className="cc-home-inline-links"><Link className="cc-home-text-link" href="/chi-sono">Conosci Dr. Botta</Link><Link className="cc-home-text-link" href="/team">Come lavora il team</Link></div></div></div></section>

<section className="cc-home-section cc-home-reading"><div className="cc-home-container"><div className="cc-home-heading"><p className="cc-home-kicker">Prima di scegliere</p><h2>Approfondisci ciò che ti serve capire.</h2><p>Il metodo, il funzionamento del percorso o una domanda sul movimento: scegli il tuo punto di partenza.</p></div><div className="cc-home-articles">{reading.map(item=><Link href={item.href} key={item.href}><span>{item.label}</span><h3>{item.title}</h3><p>{item.copy}</p><strong>{item.action}</strong></Link>)}</div><Link className="cc-home-text-link" href="/guide">Guide e strumenti per orientarti</Link></div></section>

<section className="cc-home-section cc-home-ice"><div className="cc-home-container cc-home-faq-layout"><div><p className="cc-home-kicker">I dubbi più frequenti</p><h2>Prima del colloquio,<br/><em>risposte concrete.</em></h2><Link className="cc-home-text-link" href="/domande-frequenti">Tutte le domande sul percorso</Link></div><PathwayFAQ items={getPathwayQuestions(['online','personalizzazione','perche-team','gia-provato'])}/></div></section>

<section className="cc-home-final"><ResponsiveImage src="/images/corsa-ricreativa-articolazioni.webp" alt="" sizes="100vw" loading="lazy"/><div className="cc-home-final-shade"/><div className="cc-home-container"><p className="cc-home-kicker">Il primo colloquio</p><h2>Quale attività vuoi<br/><em>tornare a fare?</em></h2><p>Confrontati con un referente del Team Corpo Capace. Puoi conoscere il funzionamento del percorso, chiarire l’assistenza e i passaggi per iniziare, prima di scegliere.</p><Link className="cc-home-button" href="/colloquio">Parla con il team del tuo obiettivo</Link></div></section>
</main><Footer/></div>}
