import { ResponsiveImage } from "../../../components/ResponsiveImage";
import { notFound } from 'next/navigation';
import { topics } from '../../../data/topics';
import { articles } from '../../../data/articles';
import { Header } from '../../../components/Header';
import { Footer } from '../../../components/Footer';
import { Breadcrumbs, pageMetadata } from '../../../lib/seo';
export function generateStaticParams(){return topics.map(t=>({topic:t.slug}));}
export async function generateMetadata({params}:{params:Promise<{topic:string}>}){const {topic}=await params;const t=topics.find(t=>t.slug===topic);return t?pageMetadata('/blog/argomenti/'+topic,t.name+': guide e approfondimenti | Dr. Botta',t.description):{};}
export default async function TopicPage({params}:{params:Promise<{topic:string}>}){const {topic}=await params;const t=topics.find(t=>t.slug===topic);if(!t)notFound();const list=articles.filter(a=>t.categories.includes(a.category));const pillar=list.find(a=>a.slug===t.pillar)??list[0];return <><Header tone="dark"/><main id="contenuto" tabIndex={-1}><section className="topic-page"><Breadcrumbs items={[{name:'Home',path:'/'},{name:'Blog',path:'/blog'},{name:t.name,path:'/blog/argomenti/'+t.slug}]}/><p className="section-label">Il blog di Corpo Capace</p><h1>{t.name}</h1><p className="topic-lead">{t.description}</p><a className="pillar-feature" href={'/blog/'+pillar.slug}><ResponsiveImage sizes="(max-width: 800px) 90vw, 43vw" loading="lazy" src={pillar.image} alt="" width="640" height="420"/><div><span className="section-label">Inizia da qui</span><h2>{pillar.title}</h2><p>{pillar.excerpt}</p><strong>Leggi l’approfondimento →</strong></div></a><h2>Altri articoli sull’argomento</h2><div className="topic-articles">{list.filter(a=>a.slug!==pillar.slug).map(a=><a href={'/blog/'+a.slug} key={a.slug}><span>{a.readingTime} di lettura</span><h3>{a.title}</h3><p>{a.kicker}</p><strong>Leggi →</strong></a>)}</div><div className="topic-bridge"><h2>Dalle informazioni al tuo percorso.</h2><p>Una lettura può orientarti. La scelta del percorso parte dalla tua situazione e da ciò che vuoi tornare a fare.</p><a className="button button--dark" href="/percorsi">Scopri come lavoriamo →</a></div></section><Footer/></main></>;}
