import { MarketingShell, Section } from '../components/Marketing';
import { PageHero } from '../components/PageHero';
import { pageMetadata } from '../lib/seo';
import { CONSULTATION_URL, CONSULTATION_LABEL } from '../lib/site';
import './percorsi.css';
import { PathwayVisuals } from './PathwayVisuals';
export const metadata=pageMetadata('/percorsi','Come funziona il percorso Corpo Capace','Dal tuo obiettivo alle capacità attuali, al programma e alla progressione: scopri come funziona Corpo Capace e il ruolo dell’assistenza del team.');
const questions = [
 ['Quanto tempo devo dedicare al percorso?','Non esiste un tempo identico per tutti. Il lavoro viene organizzato considerando il tuo obiettivo, le capacità attuali, le attività che svolgi già e il tempo realmente disponibile.'],
 ['Mi alleno già: come si integra il percorso con la mia attività?','Il lavoro tiene conto di ciò che stai già facendo. Se palestra, corsa o sport fanno parte della tua settimana, vengono considerati nel carico complessivo e nell’organizzazione del percorso.'],
 ['Cosa succede se durante il percorso la mia situazione cambia?','Il programma non viene definito una volta per tutte. La tua risposta al lavoro, ciò che diventa più gestibile e le eventuali nuove difficoltà aiutano il team a capire quando mantenere, modificare o aumentare le richieste.'],
];
export default function Page(){return <MarketingShell className="cc-how-it-works">
<PageHero page="percorsi"/>
<section className="cc-inner-intro"><div className="cc-wrap"><div className="cc-intro-grid"><div><p className="cc-label">Corpo Capace</p><h2>Il tuo obiettivo dà la direzione. Il percorso costruisce le capacità.</h2></div><div className="cc-pathway-intro-copy"><p>Corpo Capace è un percorso online di allenamento personalizzato con assistenza del team.</p><p>Partiamo da ciò che vuoi tornare a fare e da ciò che riesci a sostenere oggi. Da qui costruiamo un programma progressivo per sviluppare le capacità necessarie al tuo obiettivo e farlo evolvere nel tempo.</p></div></div><div className="cc-pathway-navigation"><nav className="cc-route-index" aria-label="Informazioni sul percorso"><a href="#come-funziona">COME SI COSTRUISCE</a><a href="#organizzazione">NELLA TUA VITA</a><a href="#chi-ti-segue">L’ASSISTENZA</a><a href="#condizioni">LE TUE DOMANDE</a></nav><a className="cc-button" href={CONSULTATION_URL}>{CONSULTATION_LABEL}</a></div></div></section>
<Section id="come-funziona" label="Come si costruisce" title="Dal tuo obiettivo al lavoro da costruire."><PathwayVisuals kind="build" items={[["IL TUO OBIETTIVO","Partiamo da ciò che vuoi tornare a fare e dalle richieste che quell’attività comporta."],["IL PUNTO DI PARTENZA","Definiamo ciò che riesci già a sostenere oggi e dove iniziano le difficoltà."],["IL TUO PROGRAMMA","Organizziamo il lavoro necessario per sviluppare progressivamente le capacità richieste dal tuo obiettivo."],["LA PROGRESSIONE","Quando ciò che stai facendo diventa gestibile, aumentiamo gradualmente le richieste e costruiamo il passo successivo."]]}/></Section>
<Section id="organizzazione" label="Totalmente personalizzato" title="Il programma entra nella tua vita."><PathwayVisuals kind="context" items={[["A casa o in palestra","Il lavoro tiene conto delle tue preferenze, dello spazio e dell’attrezzatura disponibili."],["Insieme al tuo sport","Se ti alleni già, il programma si integra con la tua attività e con gli obiettivi sportivi."],["Secondo i tuoi impegni","Il tempo disponibile e le esigenze della tua settimana fanno parte della personalizzazione. Ne parliamo insieme in consulenza."]]}/></Section>
<Section id="chi-ti-segue" label="L’assistenza è parte del percorso" title="Il confronto fa parte del lavoro."><div className="cc-assistance-intro"><p>Durante il percorso ciò che succede mentre lavori ci dà informazioni importanti.</p><p>Condividere cosa riesci a fare, dove incontri difficoltà e come rispondi alle richieste permette al team di interpretare l’andamento e mantenere il lavoro nella direzione del tuo obiettivo.</p></div><PathwayVisuals kind="support" items={[["QUELLO CHE SUCCEDE CONTA","Ciò che riesci a fare, le difficoltà che emergono e la tua risposta al lavoro diventano informazioni utili per il percorso."],["IL TEAM TI AIUTA A LEGGERLO","Il confronto serve a mettere queste informazioni nel contesto del tuo obiettivo e capire cosa significano per il lavoro che stai facendo."],["IL PASSO SUCCESSIVO HA UNA DIREZIONE","Da qui possiamo capire se mantenere il lavoro, modificarlo o aumentare gradualmente le richieste."]]}/><a className="cc-link cc-team-link" href="/team">CONOSCI IL TEAM CORPO CAPACE →</a></Section>
<section id="condizioni" className="cc-section"><div className="cc-wrap cc-practical-faq"><div><p className="cc-label">Le tue domande</p><h2>I dubbi pratici,<br/>prima di iniziare.</h2></div><div><div className="cc-faq cc-practical-accordion">{questions.map(([question,answer])=><details key={question}><summary><span>{question}</span><span className="cc-practical-icon" aria-hidden="true"/></summary><p>{answer}</p></details>)}</div><a className="cc-link" href="/domande-frequenti">TUTTE LE DOMANDE SUL PERCORSO →</a></div></div></section>
<section className="cc-section cc-dark cc-cta cc-pathway-cta"><div className="cc-wrap cc-pathway-cta-grid"><div><p className="cc-label">La tua consulenza</p><h2>Ora costruiamo il punto<br/>da cui potresti partire.</h2><p>Raccontaci cosa vuoi tornare a fare, cosa riesci a sostenere oggi e quali difficoltà incontri.</p><p>Durante la consulenza valutiamo la tua situazione, capiamo se Corpo Capace è adatto al tuo obiettivo e ti spieghiamo come potrebbe essere strutturato il percorso.</p></div><div className="cc-pathway-cta-action"><a className="cc-button cc-button-light" href={CONSULTATION_URL}>{CONSULTATION_LABEL}</a></div></div></section>
</MarketingShell>}
