import { PathwayFAQ } from '../components/PathwayFAQ';
import { getPathwayQuestions } from '../data/pathway-faq';
import Link from "next/link";
import { MarketingShell, Section, Intro, CTA, FAQ, Cards, Support } from "../components/Marketing";
import { pageMetadata } from "../lib/seo";

export const metadata=pageMetadata("/percorsi","Il percorso Corpo Capace | Programma e assistenza","Come si svolge il percorso con il team: valutazione, programma personale, video, riscontri e aggiornamenti.");
export default function Page(){return <MarketingShell><Intro page="percorsi" label="Il percorso" title="Un programma da seguire. Un team con cui confrontarti." copy="Il lavoro viene costruito sul tuo obiettivo e sulle tue possibilità. Video, indicazioni e confronti ti aiutano a svolgerlo a casa o in palestra e a segnalare ciò che non funziona."><a className="cc-button" href="#come-funziona">Guarda i passaggi ↓</a></Intro>
<Section id="come-funziona" label="Dall’inizio agli aggiornamenti" title="Come entra nella tua settimana."><Cards items={[["Obiettivo e punto di partenza","Raccogliamo storia, difficoltà e attività da recuperare. La valutazione funzionale orienta le priorità."],["Il tuo programma","Ricevi esercizi, video dimostrativi e indicazioni sulla quantità di lavoro da svolgere."],["Riscontri e aggiornamenti","Invii le esecuzioni e condividi come rispondi. Il team usa queste informazioni per adattare il programma."]]}/></Section><Support/>
<Section dark label="Cosa trovi nel percorso" title="Indicazioni, confronto e continuità."><ul className="cc-checklist"><li>Definizione dell’attività che vuoi recuperare.</li><li>Valutazione funzionale con test pertinenti.</li><li>Programma personalizzato per il contesto disponibile.</li><li>Video dimostrativi e indicazioni sul lavoro.</li><li>Invio delle esecuzioni e feedback tecnici.</li><li>Controlli e aggiornamenti del programma.</li></ul><p className="cc-small">Durata, frequenza dei confronti e modalità di assistenza vengono precisate nella proposta prima dell’adesione.</p></Section>
<Section id="domande" label="Prima di scegliere" title="Le informazioni che servono per decidere."><PathwayFAQ items={getPathwayQuestions(["personalizzazione", "tempo", "attrezzatura", "esercizio-difficile", "tempi-risultati", "prezzo"])}/><Link className="cc-link" href="/domande-frequenti">Leggi la guida completa prima di scegliere →</Link><br/><Link className="cc-link" href="/termini-e-condizioni">Leggi i termini e le condizioni di servizio →</Link></Section><CTA/></MarketingShell>}
