import Link from 'next/link';
import {MarketingShell,Intro,Section} from '../components/Marketing';
import {pageMetadata} from '../lib/seo';

export const metadata=pageMetadata('/guide','Guide Corpo Capace | Fascite plantare e movimento','Scarica la guida Corpo Capace sulla fascite plantare: cinque errori frequenti e un modo più chiaro per orientarti.');

export default function Page(){return <MarketingShell><Intro page="guide" label="Le guide Corpo Capace" title="Capire meglio, un passo alla volta." copy="Risorse pratiche per orientarti nelle scelte che riguardano movimento e attività quotidiane."/>
<Section label="La raccolta" title="La guida sulla fascite plantare"><article className="cc-guide-feature"><div className="cc-guide-feature-image"><img src="/images/fascite-plantare-corpo-capace.webp" alt="Illustrazione del piede e della fascia plantare" /></div><div className="cc-guide-feature-content"><span className="cc-guide-feature-kicker">Guida gratuita · PDF · 19 pagine</span><h3>I 5 errori per cui la fascite plantare continua a tornare</h3><p>Una guida per riconoscere le scelte che possono lasciarti nello stesso ciclo di dolore e capire quali domande portare nella valutazione del tuo caso.</p><a className="cc-button" href="/guide-fascite-plantare-corpo-capace.pdf" download="guida-fascite-plantare-corpo-capace.pdf">Scarica la guida PDF</a><a className="cc-link" href="/guide-fascite-plantare-corpo-capace.pdf" target="_blank" rel="noopener noreferrer">Apri la guida nel browser</a></div></article></Section>
<Section label="Già disponibili" title="Da dove vuoi iniziare?"><div className="cc-guide-grid"><Link href="/quiz-corpo-capace"><span>01 · Orientati</span><h3>Il quiz Corpo Capace</h3><p>Parti dall’attività che vuoi recuperare e scopri quali aspetti approfondire con il team.</p><strong>Inizia il quiz →</strong></Link><Link href="/domande-frequenti"><span>02 · Chiarisci i dubbi</span><h3>Le risposte sul percorso</h3><p>Assistenza online, impegno, risultati attesi e ruolo del team, spiegati prima di scegliere.</p><strong>Leggi le risposte →</strong></Link><Link href="/metodo"><span>03 · Comprendi</span><h3>Come funziona il metodo</h3><p>Obiettivo, punto di partenza e adattamenti: come il lavoro si collega alle tue attività.</p><strong>Esplora il metodo →</strong></Link></div><Link className="cc-link" href="/blog">Approfondisci gli argomenti nel blog →</Link></Section></MarketingShell>}
